import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navigation from '@/components/Navigation';
import QueryProvider from './provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    // description은 UI에 안 뜸. 로봇이 페이지를 해석하는 데에만 사용됨
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} flex`}>
                <Navigation />
                <QueryProvider>{children}</QueryProvider>
            </body>
        </html>
    );
}
